export { BugIcon } from "./BugIcon";
export { FlaskIcon } from "./FlaskIcon";
export { FutbolIcon } from "./FutbolIcon";
export { LiraIcon } from "./LiraIcon";
export { MoonIcon } from "./MoonIcon";
export { SpockIcon } from "./SpockIcon";
export { SunIcon } from "./SunIcon";
export { SnowflakeIcon } from "./SnowflakeIcon";
export { BoltIcon } from "./BoltIcon";
export { BrainIcon } from "./BrainIcon";
export { GamePadIcon } from "./GamePadIcon";
export { LinuxIcon } from "./LinuxIcon";
export { PuzzleIcon } from "./PuzzleIcon";
export { OtterIcon } from "./OtterIcon";
export { ChurchIcon } from "./ChurchIcon";
export { ChairIcon } from "./ChairIcon";
export { CommandIcon } from "./CommandIcon";
export {DumbellIcon} from "./DumbellIcon";
